version: "3"

services:
  backend:
    image: node:lts-iron
    restart: "always"
    volumes:
      - ./backend/:/app
    working_dir: /app
    command: bash -c "npm install && npm run dev"
    ports:
      - 3001:3001
    depends_on:
      - db
    env_file:
      - project.env

  frontend:
    image: node:lts-iron
    restart: "always"
    working_dir: /app
    command: bash -c "npm install && npm run dev --host=0.0.0.0"
    env_file:
      - project.env
    volumes:
      - ./frontend/:/app
    ports:
      - "5173:5173"

  db:
    image: postgres:13
    env_file:
      - project.env
    volumes:
      - ./backend/db/ais_db.sql:/docker-entrypoint-initdb.d/ais_db.sql
    ports:
      - "5432:5432"

  db_get:
    image: postgres:13
    env_file:
      - project.env
    volumes:
      - ./backend/db/ais_db.sql:/docker-entrypoint-initdb.d/ais_db.sql
  db_post:
    image: postgres:13
    env_file:
      - project.env
    volumes:
      - ./backend/db/ais_db.sql:/docker-entrypoint-initdb.d/ais_db.sql

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - project.env
    ports:
      - "8080:80"
